# Generated by Django 2.1.5 on 2019-02-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=255)),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('quotes', models.TextField()),
            ],
        ),
    ]
